### ISSUE TITLE
Permission request

### ISSUE THREAD

**Issue by seerge** [vddCore/Starlight#1]
Hello, great library.
Do you mind if i use it in my https://github.com/seerge/g-helper to control basics of anime matrix display ?
Thanks.

**Comment by vddCore** [comment]
Hey, glad it seems useful to you-- go ahead, it's LGPL. If the library itself has too much operational overhead for your liking there's some basic protocol documentation on the webpage I've linked in the `README.md` file.

**Comment by seerge** [comment]
Cool, animatrix is already live in g-helper
