### ISSUE TITLE
[Feature request] Time mode for Anime Matrix

### ISSUE THREAD

**Issue by Arcenus** [vddCore/Starlight#2]
I'm currently using this with G-Helper. Would it be possible to include an option to add the time mode as an Anime Matrix option? That is a mode where the Anime Matrix displays the current hour and minutes.

**Comment by vddCore** [comment]
Sorry, not a concern for Starlight - the scope of this project is providing a low-level graphics interface for other systems. Something else might use it to display more complex stuff on the AniMe Matrix.
