### ISSUE TITLE
How Can I install this Starlight ?

### ISSUE THREAD

**Issue by JackB111** [vddCore/Starlight#3]
How Can I install this Starlight ?

**Comment by vddCore** [comment]
What do you mean?

**Comment by JackB111** [comment]
I want to use g helper with starlight, but I can't figure out how to integrate and use starlight.

**Comment by vddCore** [comment]
Starlight is a driver library that can be used by other programs, it does nothing on its own. As far as I am aware, G-Helper already embeds a copy of Starlight that's divergent from this repository. If you want to use it in your own project, feel free to pull it in as a submodule.

**Comment by JackB111** [comment]
Oh okay, Thanks
